### ISSUE TITLE
Note to anyone currently looking at this

### ISSUE THREAD

**Issue by vanyasem** [WiiDatabase/Power-Off-Cartridge-Slot#2]
If you have Luma3DS installed on your 3DS, changes are, you don't actually need this homebrew anymore
This functionality is already embedded into Luma's **rosalina** menu
To bring it up, press **L+Select+DpadDown** 
Go to "System configuration", and select "Toggle power to card slot"
You can open the menu from within any game/application, which is far more convenient

**Comment by Brawl345** [comment]
Yeah this homebrew was made before Luma3DS had this functionality.
